// Generated by gencpp from file first_package/add_numberResponse.msg
// DO NOT EDIT!


#ifndef FIRST_PACKAGE_MESSAGE_ADD_NUMBERRESPONSE_H
#define FIRST_PACKAGE_MESSAGE_ADD_NUMBERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace first_package
{
template <class ContainerAllocator>
struct add_numberResponse_
{
  typedef add_numberResponse_<ContainerAllocator> Type;

  add_numberResponse_()
    : total(0)  {
    }
  add_numberResponse_(const ContainerAllocator& _alloc)
    : total(0)  {
  (void)_alloc;
    }



   typedef int64_t _total_type;
  _total_type total;





  typedef boost::shared_ptr< ::first_package::add_numberResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first_package::add_numberResponse_<ContainerAllocator> const> ConstPtr;

}; // struct add_numberResponse_

typedef ::first_package::add_numberResponse_<std::allocator<void> > add_numberResponse;

typedef boost::shared_ptr< ::first_package::add_numberResponse > add_numberResponsePtr;
typedef boost::shared_ptr< ::first_package::add_numberResponse const> add_numberResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::first_package::add_numberResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::first_package::add_numberResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::first_package::add_numberResponse_<ContainerAllocator1> & lhs, const ::first_package::add_numberResponse_<ContainerAllocator2> & rhs)
{
  return lhs.total == rhs.total;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::first_package::add_numberResponse_<ContainerAllocator1> & lhs, const ::first_package::add_numberResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace first_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::first_package::add_numberResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first_package::add_numberResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_package::add_numberResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_package::add_numberResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_package::add_numberResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_package::add_numberResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::first_package::add_numberResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f85682cd6d745599e9ac7a42c6855c71";
  }

  static const char* value(const ::first_package::add_numberResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf85682cd6d745599ULL;
  static const uint64_t static_value2 = 0xe9ac7a42c6855c71ULL;
};

template<class ContainerAllocator>
struct DataType< ::first_package::add_numberResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "first_package/add_numberResponse";
  }

  static const char* value(const ::first_package::add_numberResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::first_package::add_numberResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 total\n"
"\n"
;
  }

  static const char* value(const ::first_package::add_numberResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::first_package::add_numberResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct add_numberResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first_package::add_numberResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::first_package::add_numberResponse_<ContainerAllocator>& v)
  {
    s << indent << "total: ";
    Printer<int64_t>::stream(s, indent + "  ", v.total);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIRST_PACKAGE_MESSAGE_ADD_NUMBERRESPONSE_H
