// Generated by gencpp from file first_package/add_number.msg
// DO NOT EDIT!


#ifndef FIRST_PACKAGE_MESSAGE_ADD_NUMBER_H
#define FIRST_PACKAGE_MESSAGE_ADD_NUMBER_H

#include <ros/service_traits.h>


#include <first_package/add_numberRequest.h>
#include <first_package/add_numberResponse.h>


namespace first_package
{

struct add_number
{

typedef add_numberRequest Request;
typedef add_numberResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add_number
} // namespace first_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::first_package::add_number > {
  static const char* value()
  {
    return "5e878c160de31ef5d59d083a1ce67f56";
  }

  static const char* value(const ::first_package::add_number&) { return value(); }
};

template<>
struct DataType< ::first_package::add_number > {
  static const char* value()
  {
    return "first_package/add_number";
  }

  static const char* value(const ::first_package::add_number&) { return value(); }
};


// service_traits::MD5Sum< ::first_package::add_numberRequest> should match
// service_traits::MD5Sum< ::first_package::add_number >
template<>
struct MD5Sum< ::first_package::add_numberRequest>
{
  static const char* value()
  {
    return MD5Sum< ::first_package::add_number >::value();
  }
  static const char* value(const ::first_package::add_numberRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::first_package::add_numberRequest> should match
// service_traits::DataType< ::first_package::add_number >
template<>
struct DataType< ::first_package::add_numberRequest>
{
  static const char* value()
  {
    return DataType< ::first_package::add_number >::value();
  }
  static const char* value(const ::first_package::add_numberRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::first_package::add_numberResponse> should match
// service_traits::MD5Sum< ::first_package::add_number >
template<>
struct MD5Sum< ::first_package::add_numberResponse>
{
  static const char* value()
  {
    return MD5Sum< ::first_package::add_number >::value();
  }
  static const char* value(const ::first_package::add_numberResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::first_package::add_numberResponse> should match
// service_traits::DataType< ::first_package::add_number >
template<>
struct DataType< ::first_package::add_numberResponse>
{
  static const char* value()
  {
    return DataType< ::first_package::add_number >::value();
  }
  static const char* value(const ::first_package::add_numberResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIRST_PACKAGE_MESSAGE_ADD_NUMBER_H
